---
- hosts: localhost
  user: root
  
  vars:
    julian: "{{ lookup('file', '/opt/aaf/repo/pub_keys/julian.pub') }}"
    dalia: "{{ lookup('file', '/opt/aaf/repo/pub_keys/dalia.pub') }}"
    terry: "{{ lookup('file', '/opt/aaf/repo/pub_keys/terry.pub') }}"
    melroy: "{{ lookup('file', '/opt/aaf/repo/pub_keys/melroy.pub') }}"
    ec2: "{{ lookup('file', '/home/ec2-user/.ssh/authorized_keys') }}"

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Check Julian | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 * * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' julian.kelly@aaf.edu.au'
    state=present"
    when: 'julian == ec2'
    
  - name: Check Dalia | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' dalia.abraham@aaf.edu.au'
    state=present"
    when: 'dalia == ec2'
    
  - name: Check Terry | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' t.smith@aaf.edu.au'
    state=present"
    when: 'terry == ec2'
    
  - name: Check Melroy | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' melroy.almeida@aaf.edu.au'
    state=present"
    when: 'melroy == ec2'
