---
- hosts: localhost
  user: root
  
  vars:
    contents: "{{ lookup('file', '/etc/foo.txt') }}"

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Setup | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 * * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' julian.kelly@aaf.edu.au12345'
    state=present"
