---
- hosts: localhost
  user: root

  vars:
    julian: "{{ lookup('file', '/opt/aaf/repo/pub_keys/julian.pub') }}"
    dalia: "{{ lookup('file', '/opt/aaf/repo/pub_keys/dalia.pub') }}"
    terry: "{{ lookup('file', '/opt/aaf/repo/pub_keys/terry.pub') }}"
    melroy: "{{ lookup('file', '/opt/aaf/repo/pub_keys/melroy.pub') }}"
    ec2: "{{ lookup('file', '/home/ec2-user/.ssh/authorized_keys') }}"

  tasks:
  - include_vars: users.yml

  - name: Add users | create users, shell, home dirs
    user: name={{ item.username }} shell=/bin/bash createhome=yes comment='create with ansible'
    with_items: '{{users}}'

  - name: Setup | authorized key upload
    authorized_key: user={{ item.username }}
      key="{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
#     path='/home/{{ item.username }}/.ssh/authorized_keys'
#     manage_dir=no
    with_items: '{{users}}'

  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present"
    when: 'item.use_sudo == True'
    with_items: '{{users}}'
    
  - name: Check Cron Directory exists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron Shell
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Create Cron File if non-existent
    action: file path=/var/spool/cron/root state=touch mode=0644
    
#  - name: Check Julian | Cron Job
#    lineinfile: "dest=/var/spool/cron/root
#      regexp='{{ item.line }}'
#      line='{{ item.line }}'
#      state=present"
#    when: 'julian == ec2'
#    with_items: >
#                MAILTO:julian.kelly@aaf.edu.au
#                5 * * * * /bin/sh /opt/aaf/x/cron.sh
     
  - name: Check Julian | Cron Job
    lineinfile: "dest=/var/spool/cron/root
      regexp='^{{ item.line }} .*'
      line='{{ item.line }}'"
    when: 'julian == ec2'
    with_items:
    - 'MAILTO:julian.kelly@aaf.edu.au'
    - '5 * * * * /bin/sh /opt/aaf/x/cron.sh'
#    - 'MAILTO:julian.kelly@aaf.edu.au'
#    - 'MAILTO:julian.kelly@aaf.edu.au'

  - name: Check Dalia | Cron Job
    lineinfile: "dest=/var/spool/cron/root
      regexp='^'
      line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' dalia.abraham@aaf.edu.au'
      state=present"
    when: 'dalia == ec2'
    
  - name: Check Terry | Cron Job
    lineinfile: "dest=/var/spool/cron/root
      regexp='^'
      line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' t.smith@aaf.edu.au'
      state=present"
    when: 'terry == ec2'
    
  - name: Check Melroy | Cron Job
    lineinfile: "dest=/var/spool/cron/root
      regexp='^'
      line='30 1 * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' melroy.almeida@aaf.edu.au'
      state=present"
    when: 'melroy == ec2'
    
  - name: upgrade all packages
    yum: name=* state=latest
