---
- hosts: localhost
  user: root
  
  vars:
    julian: /opt/aaf/repo/pub_keys/julian.pub
#   - /opt/aaf/repo/pub_keys/dalia.pub
 #  - /opt/aaf/repo/pub_keys/terry.pub
#   - /opt/aaf/repo/pub_keys/melroy.pub
    ec2: /home/ec2-user/.ssh/authorized_keys

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Setup | Cron Job
    action: copy='30 * * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' julian.kelly@aaf.edu.au'
    lineinfile="dest=/var/spool/cron/root
    insertafter=EOF
    state=present"
    only_if: "'julian' == 'ec2'"
