---
- hosts: localhost
  user: root
  
  vars_files:
   - julian: /opt/aaf/repo/pub_keys/julian.pub
   - dalia: /opt/aaf/repo/pub_keys/dalia.pub
   - terry: /opt/aaf/repo/pub_keys/terry.pub
   - melroy: /opt/aaf/repo/pub_keys/melroy.pub
   - ec2: /home/ec2-user/.ssh/authorized_keys

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755

  - name: Setup | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 * * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' julian.kelly@aaf.edu.au test12345'
    state=present"
    when: 'julian == ec2'
