---
- hosts: localhost
  user: root
  
  vars:
  file:
    #/opt/aaf/repo/pub_keys/julian.pub
#   - /opt/aaf/repo/pub_keys/dalia.pub
 #  - /opt/aaf/repo/pub_keys/terry.pub
#   - /opt/aaf/repo/pub_keys/melroy.pub
    

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Setup | Cron Job
    lineinfile: "dest=/var/spool/cron/root
    insertafter=EOF
    line='30 * * * * /bin/sh /opt/aaf/x/cron.sh | mail -s 'errors' julian.kelly@aaf.edu.au12345'
    state=present"
    when: contents: '{{ lookup('file', '/home/ec2-user/.ssh/authorized_keys') }}' == contents: '{{ lookup('file', '/opt/aaf/repo/pub_keys/julian.pub') }}'
