---
- hosts: localhost
  user: root
  
  vars:
    julian: /opt/aaf/repo/pub_keys/julian.pub
#   - /opt/aaf/repo/pub_keys/dalia.pub
 #  - /opt/aaf/repo/pub_keys/terry.pub
#   - /opt/aaf/repo/pub_keys/melroy.pub
    authorized_keys: /home/ec2-user/.ssh/authorized_keys

  tasks:
  
  - name: Check Cron Directory Exsists
    action: file path=/opt/aaf/x state=directory mode=0755
    
  - name: Copy Cron File
    copy: src=/opt/aaf/repo/config.sh dest=/opt/aaf/x/cron.sh mode=0755
    
  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present"
    when: 'item.use_sudo == True'
    with_items: '{{users}}'
