---
- name: set timezone to Austalia/Brisbane
  timezone:
    name: Australia/Brisbane

# Add Packages Yum Packages Here
- name: Install Packages
  yum: pkg={{ item }} state=installed
  with_items:
    - httpd
    - mod_ssl
    - ntp
    - htop
    
- name: 'Enable Firewalld'
  service: name=firewalld state=started enabled=yes
  
- name: 'Open Apache firewall ports'
  firewalld:
    port: '{{ item }}'
    state: enabled
    permanent: yes
  with_items:
    - 80/tcp
    - 443/tcp
  register: firewall

- name: 'Enable Apache service'
  service: name=httpd state=started enabled=yes

- name: 'Restart firewalld'
  service: name=firewalld state=restarted enabled=yes
  when: firewall | changed
