---
- name: set timezone to Austalia/Brisbane
  timezone:
    name: Australia/Brisbane

- name: Install Packages
  yum: pkg={{ item }} state=installed
  with_items:
    - httpd
    - mod_ssl
    - ntp
    - htop
