---
- name: set timezone to Austalia/Brisbane
  timezone:
    name: Australia/Brisbane

- name: configure a web server firewall using firewalld
  hosts: localhost
  
  tasks:
    - name: install firewalld 
      apt: name=firewalld state=present

    - name: ensure that firewalld is started and enable at boot
      service: name=firewalld enabled=yes state=started

    - name: open up port 80 for tcp
      firewalld: port=80/tcp permanent=yes state=enabled
   
    - name: open up port 22 for tcp
      firewalld: port=22/tcp permanent=yes state=enabled
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted
