---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  tasks:
    - name: 'Create required directories for installer setup'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - '{{ installer.root }}'
        - '{{ installer.path }}'

    - name: 'Update yum packages (yum -y update)'
      yum: name=* state=latest
      when: ((server_patch is undefined) or (server_patch is none) or (server_patch=="true"))

    - name: 'Set SELinux to permissive mode'
      selinux:
        policy: targeted
        state: permissive

    - name: 'Install required packages'
      yum: pkg={{ item }} state=installed
      with_items:
        - httpd
        - mod_ssl
        - MySQL-python
        - ntp
        - expect

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include_vars: users.yml

    - name: Add users | create users, shell, home dirs
      user: name={{ item.username }} shell=/bin/bash createhome=yes comment='create with ansible'
      with_items: '{{users}}'

    -  name: Setup | authorized key upload
       authorized_key: user={{ item.username }}
        key="{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
#      path='/home/{{ item.username }}/.ssh/authorized_keys'
#      manage_dir=no
       with_items: '{{users}}'

    - name: Sudoers | update sudoers file and validate
      lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present"
      when: '{{ item.use_sudo }} == True'
      with_items: '{{users}}'

  handlers:
    - name: Restart idp
      service:
        name: idp
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
